### PR TITLE
Update wayland.xml to 1.21.92

### PR DESCRIPTION
**Pull request by chrisduerr**
I think the most noteworthy change here is probably the addition of `preferred_scale`, which I think makes some sense to integrate considering fractional scale is already supported and implementing preferred scale on top of that should be pretty simple for compositors.

### CODE REVIEW

**Comment by vberger** [comment]
1.21.92 is a beta release, shouldn't we wait for the proper 1.22 release?

In any case, could you add changelog entries to wayland-client and wayland-server covering this update?

**Comment by chrisduerr** [comment]
> 1.21.92 is a beta release, shouldn't we wait for the proper 1.22 release?

That's something I was pondering myself, I'm not sure about your policy on this.

To me it seems unlikely that there will be major changes to protocols after they've been officially released, but I'm not familiar with Wayland's track record here.

But since new additions don't introduce breaking changes to existing protocols, I think it should be fine to expose unstable additions like this. Wayland protocol extensions are already heavily used in unstable revisions and I think since most compositor/client developers directly using this are likely looking at the protocols themselves, they can make their own decisions about relying on unstable/beta versions.

**Comment by elinorbgr** [comment]
Ok, so 1.22 has been released now, with no changes since 1.21.92. I'm good with merging this, maybe let's just adjust the changelogs accordingly?

**Comment by elinorbgr** [comment]
Thanks

**Pull request merged**
