### PR TITLE
Update wayland-protocols to 1.32

### PR DESCRIPTION
**Pull request by WhyNotHugo**
This relies on unreleased (but already merged) changes upstream. I'm not sure if you'd rather merge this now or wait for an upstream release, but I'm sharing this at this point since I want to write application code that uses this protocol.

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
CI failures seem unrelated.

**Comment by WhyNotHugo** [comment]
> In general I prefer to follow wayland-protocols upstream releases.

Of course, we can wait until there is a stable release before merging this.

I mostly created this branch to unblock myself so that I can start using this protocol on an application of mine (shotman), but figured I might avoid someone else duplicating the work by leaving this PR open here.

I don't know when an upstream release will happen.

**Comment by kchibisov** [comment]
fyi, the protocol is already available in sctk branch, given that it was used as a reference for wayland-protocols in the first place https://github.com/Smithay/client-toolkit/pull/381

**Comment by i509VCB** [comment]
There has been a wayland-protocols release recently if I recall, so we probably want to do a full update.

**Comment by i509VCB** [comment]
If possible could you also add the other two protocols introduced in 1.32?

**Comment by WhyNotHugo** [comment]
Since rebasing on `master`, none of the docs are generating properly for me.

Cursor shape is empty:

image

But so are other protocols like idle_notify:

image

**Comment by WhyNotHugo** [comment]
Updated PR with all protocols from wayland-protocols 1.32.

**Comment by kchibisov** [comment]
@i509VCB ping.

**Review by i509VCB — APPROVED** [review]
Apparently `log` raised MSRV so msrv build fails.

**Comment by WhyNotHugo** [comment]
The cause of the CI failure is in https://github.com/Smithay/wayland-rs/blob/master/.gitignore#L3

Because there is no lockfile (and CI is also not instructed to use `--frozen`), the latest version of dependencies is pulled on each run.

The line I've linked should be removed and the lockfile should be committed to the repository to prevent this kind of breakage from happening again. To deal with this particular issue, it's either possible to bump the MSRV or pin an older `log` crate. I can send a PR for either alternative.

**Pull request merged**
