### PR TITLE
Make wayland_server::create_event_loop public

### PR DESCRIPTION
**Pull request by myfreeweb**
It is useful for compositors:

https://github.com/myfreeweb/weston-rs/blob/8222ffab43a41a54ef107454558ca495cbe4d009/weston-rs/src/display.rs#L32-L34

### CODE REVIEW

**Comment by myfreeweb** [comment]
hm, I'm actually creating the display myself. I'm not sure why I have my own `wl_display` wrapper... oh, probably because I want to create new `Display` references from a raw `*mut wl_display`.

**Comment by myfreeweb** [comment]
Oh. Actually. I still need this. I have the Rust side implementing an API that Weston calls into.

But maybe for `EventLoopHandle` instead of `EventLoop`

**Comment by vberger** [comment]
If you need it only for `EventLoopHandle` (registering & implementing new resources, I guess ?), then it is possible that the incoming 0.20 rework (see #165 ) will solve your issue, as it largely decouples resources and implementing them from the `EventLoop` type, and `EventLoopHandle` is completely removed. This PR is almost ready, and I'm just checking the few potentials missing bits by working on https://github.com/Smithay/smithay/pull/88 using it.

Overall, this reworks does break a lot of things, but should make many things easier to integrate and handle I believe. Maybe if you summarize the precise uses you need `EventLoop` and `EventLoopHandle` for, I can see if some adaptations to wayland-rs 0.20 should be done accordingly?

**Comment by myfreeweb** [comment]
> registering & implementing new resources, I guess

No. I just need to call `add_fd_event_source` in a Rust impl that's called from C (libweston).

I just realized though, I can actually use `user_data` on libweston's compositor object to pass the Rust event loop object through the C world!...

**Comment by myfreeweb** [comment]
[Done](https://github.com/myfreeweb/weston-rs/commit/5223e65bd0b6f2659f972d59f18a84a55f7479e2).

I guess I was also slightly confused by the lack of a `run` method on your `Display`, but running the `EventLoop` works fine.

**Pull request closed without merging**
