### PR TITLE
Remove a pointless allocation

### PR DESCRIPTION
**Pull request by SUPERCILEX**
The stack size is 152 bytes which is teeny.

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
None of the failures look related.

**Comment by ids1024** [comment]
Yeah, looks like https://github.com/Smithay/wayland-rs/pull/772 has fixes for the CI errors here.

I thought there was a reason this used a vec... and it looks like I was right, but this has been fixed in Rustix: https://github.com/bytecodealliance/rustix/pull/889. (Which I now remember seeing.)

I guess we should update the `rustix` dependency to explictly require  0.38.21 or newer? (I think this would be failing in the `check-minimal` CI test because of that; if it wasn't failing earlier for unrelated reasons.)

**Comment by SUPERCILEX** [comment]
Bumping rustix sounds good and I'll wait for the other PR.

**Comment by ids1024** [comment]
That PR is merged.

If CI passes after rebasing and updating the `rustix` dep version, this looks good.

**Comment by SUPERCILEX** [comment]
All green

**Review by ids1024 — APPROVED** [review]

**Comment by ids1024** [comment]
Thanks!

**Pull request merged**
