### PR TITLE
Implement TODO

### PR DESCRIPTION
**Pull request by WhyNotHugo**
Came across this TODO trying to understand the logic in here and figured it was a pretty trivial fix.

### CODE REVIEW

**Comment by elinorbgr** [comment]
Unfortunately, this change would bump the MSRV from 1.59 to 1.62, and I don't think this is by itself a sufficient reason to do it. :sweat_smile:

**Comment by WhyNotHugo** [comment]
Odd, the error message indicates that this is due to the `raw-window-handle` crate:

> error: package `raw-window-handle v0.5.2` cannot be built because it requires rustc 1.64 or newer, while the currently active rustc version is 1.59.0

But yeah, [`then_some`](https://doc.rust-lang.org/std/primitive.bool.html#method.then_some) requires 1.62.

I'll just leave this as draft until the MSRV is pushed for some other reason.

**Comment by WhyNotHugo** [comment]
This might actually happen soon due to https://github.com/Smithay/wayland-rs/pull/610

**Comment by elinorbgr** [comment]
> error: package raw-window-handle v0.5.2 cannot be built because it requires rustc 1.64 or newer, while the currently active rustc version is 1.59.0

Yeah, as said on the other PR you linked this is actually a CI issue, I don't plan to bump the MSRV because of an optional dep.

**Comment by elinorbgr** [comment]
Closing this following #617

**Comment by WhyNotHugo** [comment]
I left this in draft because it relied on a newer MSRV. Is the change itself entirely unwanted?

**Pull request closed without merging**
