### PR TITLE
sys: add wl_listener and wl_signal

### PR DESCRIPTION
**Pull request by vberger**
cc #116

### CODE REVIEW

**Comment by vberger** [comment]
This is an attempt at implementing the `wl_signal_*` fucntions from wayland-server's headers in rust.

We need to make sure:

- `offset_of!(..)` is not UB, and if it is, can we work around it?
- the functions are correctly implemented, according to the reference impl of wayland-server

**Comment by vberger** [comment]
@Timidger it looks like you are interested in this, your eyes would be welcome!

**Comment by Timidger** [comment]
I appreciate this, this stuff is super helpful for my wlroots wrapper. 

Haven't had a chance to double check the implementation against the reference, but a quick glance the macros at least look right. 

In regards to the safety of `offset_of!`, it _should_ be safe so long as the struct is `#[repr(C)]`. Without that, Rust can reorder the struct ordering as an optimization. 

Either way though this will rely on the internal memory representation of Rust structs. Making them use the C model means that shouldn't change.

**Comment by vberger** [comment]
My wary regarding `offset_of!()` is that we are kind-of dereferencing a null pointer, isn't that UB?

**Comment by Timidger** [comment]
According to [this stackoverflow answer](https://stackoverflow.com/questions/38819569/how-to-get-a-pointer-to-a-containing-struct-from-a-pointer-to-a-member) (which is where I got that particular snippet), this is a simplification on the solution posted by the questioner. The original is a little more explicit and is definitely not UB because he just does straight pointer arithmetic.

You're correct though that this does seem kind of suspect...I understand the logic done though. I played around with it my self, and I think the magic is that we immediantly convert the field to a pointer, so that Rust is smart enough to not actually dereference the pointer ever actually. It is able to see (even with no optimizations turned on) that we aren't asking for the value of the struct at memory address 0, we are asking for the memory address of the field of the struct that resides at memory address 0. That way, we are just doing basic pointer arithmetic.

[Here is me playing around with it on the playground](https://is.gd/okCbIT). Note the cases where UB can be invoked, but with the code as-is it works because we aren't ever actually de referencing null pointers (even though it looks like we are).

**Comment by vberger** [comment]
Okay, in this case I'll merge this and release a new version.

I hope if there is any bug in this, it won't be too hard to hunt... I've tried to follow closely the C code, though, so it should be ok I guess.

**Comment by Timidger** [comment]
I'll be making heavy use if it, so if I notice anything strange I'll be sure to report it here, and try to provide a fix

**Pull request merged**
