### PR TITLE
Replace `lazy_static` with `once_cell`

### PR DESCRIPTION
**Pull request by daxpedda**
This replaces [`lazy_static`](https://crates.io/crates/lazy_static) with [`once_cell`](https://crates.io/crates/once_cell). See #604 for more information.

Initially I was intending to not expose the `Lazy` type like we did before with types generated by `lazy_static`, but turned out that libraries like [`dlib`](https://crates.io/crates/dlib) don't play well with functions, so I left it as is. Happy to change it to a function though.

Because of the currently exposed `lazy_static` types, this is a breaking change.

Fixes https://github.com/Smithay/wayland-rs/issues/604.
Requires https://github.com/elinorbgr/dlib/pull/21.

### CODE REVIEW

**Comment by daxpedda** [comment]
CI fails with the same errors as on master, unrelated to this PR.

**Comment by notgull** [comment]
I'd also like not to expose `once_cell`, since it may be replaced by `std` in the near future. It would be nice if we could just rework `dlib` to support this use case.

**Comment by daxpedda** [comment]
Made https://github.com/elinorbgr/dlib/pull/21 to address this.

**Comment by elinorbgr** [comment]
The dlib PR is merged, and I released dlib 0.5.1 with that change.

**Comment by daxpedda** [comment]
Hm, I guess we can just ignore the code coverage failure here?

**Comment by elinorbgr** [comment]
Ah wait, could you just add an entry to wayland-sys's changelog? this is a breaking change after all.

**Comment by daxpedda** [comment]
Done.

**Comment by elinorbgr** [comment]
Perfect, thanks!

**Pull request merged**
