### PR TITLE
Update `wayland-protocols` to 1.34

### PR DESCRIPTION
**Pull request by ids1024**
Adds linux-drm-syncobj-v1.

### CODE REVIEW

**Comment by ids1024** [comment]
Oh, I guess there are a couple more protocols to add. That were merge merged since 1.33.

**Comment by ids1024** [comment]
Added the other two protocols, and doc comments.

**Review by elinorbgr — APPROVED** [review]
LGTM, I'll look at the CI failure that is unreleated, before e merge this.

**Comment by ids1024** [comment]
CI is passing after rebasing.

**Pull request merged**
