### PR TITLE
backend: enable some smallvec features

### PR DESCRIPTION
**Pull request by i509VCB**
Since wayland-rs depends on 1.53, union, const_generics and const_new may be enabled.

### CODE REVIEW

**Comment by vberger** [comment]
What do we gain by enabling those?

**Comment by i509VCB** [comment]
> What do we gain by enabling those?

The union feature decreases the size of a SmallVec by one machine word. So 8 bytes smaller on a 64-bit machine.

**Comment by vberger** [comment]
Ok, but we don't use the `const_generics` nor `const_new`, so why enable them?

**Comment by i509VCB** [comment]
const_generics is for `impl<T, const N: usize> Array for [T; N] { ... }` it replaces the huge macro inside smallvec for the fixed number of array sizes. We don't use an array that large to benefit, but it is more idomatic for the implementation.

const_new probably isnt necessary.

**Pull request merged**
