### PR TITLE
protocol: org-kde-kwin-idle-v1 added to misc. (0.30.x)

### PR DESCRIPTION
**Pull request by Shinyzenith**

### CODE REVIEW

**Comment by Drakulix** [comment]
Does this belong to misc or should be create a new namespace for kde-protocols?

**Comment by Shinyzenith** [comment]
> Does this belong to misc or should be create a new namespace for kde-protocols?

Probably best to create kde-protocols in my opinion.

**Comment by Shinyzenith** [comment]
Should I go ahead and make it?

**Comment by Drakulix** [comment]
That is something @vberger should likely decide, I just wanted to bring it up, before this gets merged.

**Comment by kchibisov** [comment]
Also, can't we use kde protocols as git submodule, like we do for wlr protocols? And generate all of them?

**Comment by Shinyzenith** [comment]
> Also, can't we use kde protocols as git submodule, like we do for wlr protocols? And generate all of them?

If the idea is allowed by Victor, I'll go ahead and force push that change to this pr.

**Comment by vberger** [comment]
How much of a public api are the KDE protocols considered by KDE?

**Comment by Shinyzenith** [comment]
> How much of a public api are the KDE protocols considered by KDE?

I'm afraid I don't know the answer to that 😔.

**Comment by vberger** [comment]
Basically, my point is that I'm reluctant to integrating them into the `wayland-protocols` crate if there are not at least some stability guarantees on these protocols, which I fear might not be there if they are considered as implementation details by KDE...

**Comment by vberger** [comment]
Closing in favor of #478 which introduces a `wayland-protocols-plasma` crate

**Pull request closed without merging**
