### PR TITLE
Use `BorrowedFd` in arguments

### PR DESCRIPTION
**Pull request by ids1024**
Implementation of https://github.com/Smithay/wayland-rs/issues/592.

This is required for IO safety. Or perhaps `AsFd` generics would be useful.

This will be a breaking API change, and require Rust 1.65.

Currently `wayland-client` compiles here, but server-side needs the same changes, and things need to be cleaned up a bit.

### CODE REVIEW

**Comment by ids1024** [comment]
Hm, an awkward API stability concern here: adding `Request`/`Event` enums are non-exhastive. So adding a variant is considered a non-breaking change. But as this is currently implemented in this PR, adding a variant with an FD adds a type generic, which is breaking.

That is needed because an enum can't have a type generic unless a variant uses that type parameter. Maybe if it's non-exhaustive anyway, it could have a variant that's never constructed with a `PhantomData`? And an uninhabited type for good measure.

**Comment by ids1024** [comment]
Currently `Request`/`Event` types and methods also accept `String` and `Vec<u8>` instead of `&str` and `&[u8]`. Not that much of an issue since those types aren't the most common in Wayland, but presumably with a GAT here those could also be changed, avoiding an extra allocation and provide a more idiomatic API.

**Comment by ids1024** [comment]
Added generation of a `#doc(hidden)` phantom variant for API stability.

This should be good now.

**Review by elinorbgr — APPROVED** [review]
That's a solid PR, thanks!

**Pull request merged**
