### PR TITLE
[feature]Add ext_session_lock to staging protocols

### PR DESCRIPTION
**Pull request by Shinyzenith**

### CODE REVIEW

**Comment by i509VCB** [comment]
We should probably stick to release versions of Wayland-protocols, meaning the submodule should be updated to d3249868.

Note that master is 0.30, you'll want to target the 0.29.x branch otherwise.

**Comment by Shinyzenith** [comment]
> We should probably stick to release versions of Wayland-protocols, meaning the submodule should be updated to d3249868.
> 
> Note that master is 0.30, you'll want to target the 0.29.x branch otherwise.

I have updated the submodule.

**Comment by Shinyzenith** [comment]
Should I close this pr and send it to 0.30 branch?

**Comment by i509VCB** [comment]
If you want to use the protocol with the current non alpha crates you'll probably want to make another pull request for those versions.

**Comment by Shinyzenith** [comment]
> If you want to use the protocol with the current non alpha crates you'll probably want to make another pull request for those versions.

Alright, I'll switch to 0.29x as I intend to use this protocol.

**Pull request closed without merging**
